### ISSUE TITLE
True coerces to 1

### ISSUE THREAD

**Issue by nheir** [sagemath/sage-combinat-widgets#13]
In 

https://github.com/sagemath/sage-combinat-widgets/blob/dcd47e465bcc76332ef49294d57e731e75ff8088/sage_combinat_widgets/grid_view_editor.py#L725-L726

prefer `val is True` over `val == True` (same with `False`) because of integer coercion

like

https://github.com/sagemath/sage-combinat-widgets/blob/dcd47e465bcc76332ef49294d57e731e75ff8088/sage_combinat_widgets/grid_view_editor.py#L677-L678

**Comment by zerline** [comment]
Fixed by https://github.com/sagemath/sage-combinat-widgets/commit/e32cb61cb8af16f3b41ec9f7d2a51ad90a4caed9 and https://github.com/sagemath/sage-combinat-widgets/commit/4858e3d93c45e4ddeb3e232dd2e620f999786d4b
