### ISSUE TITLE
Potential Substitute for add_traits?

### ISSUE THREAD

**Issue by rmorshea** [sagemath/sage-combinat-widgets#2]
@zerline I took a look at why you need [`add_traits`](https://github.com/sagemath/sage-combinat-widgets/blob/master/sage_combinat_widgets/tableau_widget.py#L106) and quickly realized the dynamic nature of your use case... In my opinion this is where `traitlets` breaks down - the limitations of `add_traits` shown in https://github.com/ipython/traitlets/issues/500 demonstrate that `traitlets` simply wasn't designed to be as flexible as you need it to be.

With that said, while working on https://github.com/ipython/traitlets/pull/466 I created a library called [`spectate`](https://github.com/rmorshea/spectate) that you might find useful - it was specifically built to capture changes that are made to mutable data types.

I don't think I understand exactly what you're trying to do with `add_traits`, but check out this example and see if you might be able to avoid `add_traits` with it:

```python
from spectate import mvc

d = mvc.Dict()

@mvc.view(d)
def printer(event):
    print(event)

d['a'] = 1
```

```
{'key': 'a', 'old': Undefined, 'new': 1}
```

At the moment, the example above uses a feature that is in the most recent release of `spectate`, but is untested, and marked as experimental. If you're interested in using it, I'd be happy to make sure it's tested.

**Comment by rmorshea** [comment]
@zerline I think the way to work around your problem is to store all of the cell values in one trait:

```python
class TableauWidget(...):
    # make this a private attribute
    _cell_values = Dict().tag(sync=True)
    # I assume you sync this data with a frontend view
```

You could then register an observer on the `TCell.value` trait object that updates the `_call_values` trait every time it changes:

```python
class TCell(...):
    
    @observe("value")
    def _value_changed(self, change):
        # need to copy here to trigger notifications on parent
        cells = self.parent._cell_values.copy()
        cells[self.coord] = change.new
        self.parent._cell_values = cells
```

This way you don't need to create a whole bunch of traits at the time you instantiate the `TableauWidget`.

Perhaps there's some significance to `cell_<x>_<y>` trait names, but the benefits you get from avoiding `add_traits` seem like they would be worth doing some downstream work to use a collective `_cell_values` trait.

**Comment by zerline** [comment]
Thanks @rmorshea 
Yet things work perfectly the way they are now ..
(with you pull request https://github.com/ipython/traitlets/pull/501 would be even better, and I support this pull request warmly)
I might consider using a dict in a future version.
Regards,

**Comment by rmorshea** [comment]
An even simpler optimization I just realized would be to ensure that you only call `add_traits` once. Right now [`add_traits` is called](https://github.com/sagemath/sage-combinat-widgets/blob/master/sage_combinat_widgets/tableau_widget.py#L106) once for every cell. If you instead collected the new traits from the loop into a dict and made a single call to `add_traits` afterward, the size of your MRO would be much smaller.

**Comment by zerline** [comment]
Yes, you'fre right. And I'm doing exactly that (on branch develop, will be on master a little later, sorry, there's a lot to do).
Regards
